# Uncomment the next line to define a global platform for your project
# platform :ios, '16.0'

target 'aac-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for aac-ios
    pod 'Firebase/Auth' 


  target 'aac-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'aac-iosUITests' do
    # Pods for testing
  end

end
